---
- name: restart all go services
  shell: ls -1 /etc/default/go-agent? /etc/default/go-server
  register: go_services
  notify:
     - restart go service
     - ensure go-server running

- name: restart all agents
  shell: ls -1 /etc/default/go-agent?
  register: go_services
  notify:
     - restart go service

- name: restart go service
  service: name={{ item | basename }} state=restarted
  with_items: go_services.stdout_lines

- name: restart go-server
  sudo: yes
  service: name=go-server state=restarted
  notify:
     - ensure go-server running

- name: ensure go-server running
  wait_for: port={{ GOCD_SERVER_PORT }} timeout=180 delay=10

- name: restart firewalld
  sudo: yes
  service: name=firewalld state=restarted
